// apps/demo-react/src/App.tsx
import { useEffect, useCallback } from 'react';
import KanjoPlayerDemo from './components/KanjoPlayerDemo';

function App() {
  const handleCustomEvent = useCallback((e: Event) => {
    const detail = (e as CustomEvent).detail;
    if (detail.eventKey === 'set_dark_mode') {
      document.documentElement.classList.add('dark-mode');
    } else if (detail.eventKey === 'set_light_mode') {
      document.documentElement.classList.remove('dark-mode');
    }
  }, []);

  useEffect(() => {
    document.addEventListener('kanjo-custom-event', handleCustomEvent);
    return () => {
      document.removeEventListener('kanjo-custom-event', handleCustomEvent);
    };
  }, [handleCustomEvent]);

  return (
    <>
      <div className="external-links">
        <a
          href="https://github.com/underactive/kanjoplayer"
          target="_blank"
          rel="noopener"
          title="GitHub Repository"
        >
          <svg width="16" height="16" viewBox="0 0 16 16" fill="currentColor">
            <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.013 8.013 0 0016 8c0-4.42-3.58-8-8-8z" />
          </svg>
        </a>
        <a
          href="https://www.npmjs.com/package/kanjo-player"
          target="_blank"
          rel="noopener"
          title="npm Package"
        >
          <svg width="16" height="16" viewBox="0 0 16 16" fill="currentColor">
            <path d="M0 0v16h16V0H0zm3 3h10v10H8V5.5H5.5V13H3V3z" />
          </svg>
        </a>
      </div>
      <div className="app">
        <header>
          <h1>KanjoPlayer Demo</h1>
          <nav className="demo-links">
            <a href="/">Plain HTML</a>
            <a href="/vue/">Vue</a>
            <a href="/react/" className="active">
              React
            </a>
            <a href="/svelte/">Svelte</a>
          </nav>
        </header>
        <main>
          <KanjoPlayerDemo />
        </main>
      </div>
    </>
  );
}

export default App;

// apps/demo-svelte/src/App.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte'
  import KanjoPlayerDemo from './lib/KanjoPlayerDemo.svelte'

  function handleCustomEvent(e: Event) {
    const detail = (e as CustomEvent).detail
    if (detail.eventKey === 'set_dark_mode') {
      document.documentElement.classList.add('dark-mode')
    } else if (detail.eventKey === 'set_light_mode') {
      document.documentElement.classList.remove('dark-mode')
    }
  }

  onMount(() => {
    document.addEventListener('kanjo-custom-event', handleCustomEvent)
  })

  onDestroy(() => {
    document.removeEventListener('kanjo-custom-event', handleCustomEvent)
  })
</script>

<div class="external-links">
  <a href="https://github.com/underactive/kanjoplayer" target="_blank" rel="noopener" title="GitHub Repository">
    <svg width="16" height="16" viewBox="0 0 16 16" fill="currentColor"><path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.013 8.013 0 0016 8c0-4.42-3.58-8-8-8z"/></svg>
  </a>
  <a href="https://www.npmjs.com/package/kanjo-player" target="_blank" rel="noopener" title="npm Package">
    <svg width="16" height="16" viewBox="0 0 16 16" fill="currentColor"><path d="M0 0v16h16V0H0zm3 3h10v10H8V5.5H5.5V13H3V3z"/></svg>
  </a>
</div>
<div class="app">
  <header>
    <h1>KanjoPlayer Demo</h1>
    <nav class="demo-links">
      <a href="/">Plain HTML</a>
      <a href="/vue/">Vue</a>
      <a href="/react/">React</a>
      <a href="/svelte/" class="active">Svelte</a>
    </nav>
  </header>
  <main>
    <KanjoPlayerDemo />
  </main>
</div>
